server:
  port: 8989
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/local
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true